### ISSUE TITLE
It would be great if this project supported Android

### ISSUE THREAD

**Issue by appcellphone** [meemknight/ourCraft#2]
@meemknight 
Hello, I found this great project while watching your YouTube. Can you help me build a game for the Android platform? Converting OpenGL to OpenGL ES is quite complicated, and I hope you can assist me! Thank you very much!

**Comment by meemknight** [comment]
Unfortunately, I haven't done android so far so I don't have experience. Consider using railib maybe. Or if you have specific questions about just converting from opengl to opengl es we can talk on my discord:
https://discord.gg/eehehsPAka
