### ISSUE TITLE
Mods?

### ISSUE THREAD

**Issue by portal2707070** [meemknight/ourCraft#20]
Will mods be added?

**Comment by meemknight** [comment]
yess, I already have cats pigs and zombies and they also have some basic AI. If you want to discuss some more you can find me on my discord server
https://discord.gg/eehehsPAka

**Comment by meemknight** [comment]
I misread yout comment :))))) I read mobs instead of mods. So the short answer is no, but who know maybe some people want to change the source code a lot in order to make a mod for the game.
