### ISSUE TITLE
Linux support planed?

### ISSUE THREAD

**Issue by 33bar33k** [meemknight/ourCraft#3]
I would love to play our craft but I am on linux and sadly i dont know c++ enough to try to implement linux support

**Comment by meemknight** [comment]
I'm actually working on this, it should compile on Linux soon 💪

**Comment by meemknight** [comment]
update it should be working or almost working (one or 2 small problems max) on Linux. I won't be able to do a lot of testing so if you give it a try let me know if you have problems
